fc_check implementation

diff --git a/tools/fc_check b/tools/fc_check
--- a/tools/fc_check
+++ b/tools/fc_check
@@ -1,7 +1,33 @@
-```
-├───artifacts              : folder to store all output artifacts of main code/scripts
-│       hukamnama.json     : file to store data about hukamnamas
-├───src                    : main code goes in this directory
-│       main.py            : main code goes in this file
-├───test                   : test code, and other related files/code go in this directory
-│   └───src                : main test code goes in this dir
+#!/bin/sh
+# ------------------------------------------------------------------------------
+# fc_check - Check for string literal to block github merge into main.
+#
+# September 2022, Gurkiran Singh
+#
+# Copyright (c) 2022
+# All rights reserved.
+# ------------------------------------------------------------------------------
+
+FC_STRING1="FAIL_"
+FC_STRING2="COMMIT"
+FC_STRING="$FC_STRING1$FC_STRING2"
+
+EXCLUDE_DIR=".git/"
+
+CMD="grep -rni $FC_STRING --exclude-dir=$EXCLUDE_DIR"
+OUTPUT=$(eval "$CMD")
+RC=$?
+
+if [ $RC -eq 0 ] # matching files found
+then
+    echo "$FC_STRING strings found. Please remove:"
+    echo $OUTPUT
+elif [ $RC -eq 1 ] # matching files not found
+then
+    echo "No files found with '$FC_STRING'."
+else
+    echo "Error running bash command."
+    echo "  Command ran: $CMD"
+    echo "  Output: $OUTPUT"
+    echo "  Return code $RC"
+fi
